# Generated by Django 5.1 on 2024-08-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="tag",
            new_name="tags",
        ),
    ]
